name: "Upload Asset"
description: "Move binary, create ZIP archive, and upload as release asset"
inputs:
  exe_dir:
    required: true
  exe_name:
    required: true
  tag_name:
    required: true
  target:
    required: true
runs:
  using: "composite"
  env:
    ASSET_PATH: ${{ inputs.target }}-${{ inputs.exe_name }}
  steps:
    - name: Move Binary
      env:
      run: mv ${{ inputs.exe_dir }}/${{ inputs.exe_name }} ${{ env.ASSET_PATH }}

    - name: Create ZIP Archive
      shell: bash
      if: runner.os != 'Windows'
      env:
      run: zip ${{ env.ASSET_PATH }}.zip ${{ env.ASSET_PATH }}

    - name: Create ZIP Archive (Windows)
      shell: pwsh
      if: runner.os == 'Windows'
      env:
      run: Compress-Archive ${{ env.ASSET_PATH }} ${{ env.ASSET_PATH }}.zip

    - name: Upload Release Asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload ${{ inputs.tag_name }} ${{ env.ASSET_PATH }}
